suites:
  dacapo2006:
    type: DaCapo
    release: "2006"
    path: /usr/share/benchmarks/dacapo/dacapo-2006-10-MR2.jar
    minheap: adoptopenjdk-15-G1
    minheap_values:
      adoptopenjdk-15-G1:
        antlr: 5
        chart: 21
        eclipse: 25
        hsqldb: 135
    timing_iteration: 3
    timeout: 120
  dacapobach:
    type: DaCapo
    release: "9.12"
    path: /usr/share/benchmarks/dacapo/dacapo-9.12-bach.jar
    minheap: adoptopenjdk-15-G1
    minheap_values:
      adoptopenjdk-15-G1:
        avrora: 5
        fop: 37
        jython: 31
        luindex: 7
        pmd: 41
        sunflow: 17
        xalan: 8
    timing_iteration: 3
    timeout: 120
  dacapobach-mr1:
    type: DaCapo
    release: "9.12"
    path: /usr/share/benchmarks/dacapo/dacapo-9.12-MR1-bach.jar
    minheap: adoptopenjdk-15-G1
    minheap_values:
      adoptopenjdk-15-G1:
        avrora: 5
        fop: 39
        jython: 32
        luindex: 9
        pmd: 41
        sunflow: 17
        xalan: 10
    timing_iteration: 3
    timeout: 120
  dacapobach-mr1-java6:
    type: DaCapo
    release: "9.12"
    path: /usr/share/benchmarks/dacapo/dacapo-9.12-MR1-bach-java6.jar
    timing_iteration: 3
    timeout: 120
    minheap_values: {}
  dacapochopin-69a704e:
    type: DaCapo
    release: evaluation
    path: /usr/share/benchmarks/dacapo/dacapo-evaluation-git-69a704e.jar
    minheap: adoptopenjdk-15-G1
    minheap_values:
      adoptopenjdk-15-G1:
        avrora: 7
        batik: 253
        biojava: 191
        cassandra: 89
        eclipse: 437
        fop: 19
        graphchi: 255
        h2: 1154
        h2o: 73
        jme: 55
        jython: 37
        # Java version '15.0.2' is incompatable with kafka: Kafka currently requires Java 8 due to 'java.lang.NoClassDefFoundError: javax/activation/DataSource' error for more recent Java releases.
        # kafka: inf
        luindex: 42
        lusearch: 23
        pmd: 243
        sunflow: 33
        tradebeans: 169
        tradesoap: 133
        tomcat: 25
        xalan: 9
        zxing: 96
      temurin-17-G1:
        avrora: 7
        batik: 189
        biojava: 95
        eclipse: 411
        fop: 15
        graphchi: 255
        h2: 773
        jme: 29
        jython: 25
        luindex: 42
        lusearch: 21
        pmd: 156
        sunflow: 29
        tomcat: 21
        tradebeans: 131
        tradesoap: 103
        xalan: 8
        zxing: 97
    timing_iteration: 3
    timeout: 120
  dacapochopin-29a657f:
    type: DaCapo
    release: evaluation
    path: /usr/share/benchmarks/dacapo/dacapo-evaluation-git-29a657f.jar
    minheap: adoptopenjdk-15-G1
    minheap_values:
      adoptopenjdk-15-G1:
        avrora: 7
        batik: 253
        biojava: 191
        cassandra: 89
        eclipse: 437
        fop: 19
        graphchi: 255
        h2: 1154
        h2o: 73
        jme: 55
        jython: 37
        # Java version '15.0.2' is incompatable with kafka: Kafka currently requires Java 8 due to 'java.lang.NoClassDefFoundError: javax/activation/DataSource' error for more recent Java releases.
        # kafka: inf
        luindex: 42
        lusearch: 23
        pmd: 243
        sunflow: 33
        tradebeans: 169
        tradesoap: 133
        tomcat: 25
        xalan: 9
        zxing: 96
      temurin-17-G1:
        avrora: 7
        batik: 189
        biojava: 95
        eclipse: 411
        fop: 15
        graphchi: 255
        h2: 773
        jme: 29
        jython: 25
        luindex: 42
        lusearch: 21
        pmd: 156
        sunflow: 29
        tomcat: 21
        tradebeans: 131
        tradesoap: 103
        xalan: 8
        zxing: 97
    timing_iteration: 3
    timeout: 120
