modifiers:
  tph:
    type: JVMArg
    val: "-XX:+UseThirdPartyHeap"
  c2:
    type: JVMArg
    val: "-XX:-TieredCompilation -Xcomp"
    excludes:
      dacapochopin-69a704e:
        - tradebeans
        - tradesoap
  ms:
    type: JVMArg
    val: "-XX:MetaspaceSize=500M -XX:+DisableExplicitGC"
  s:
    type: JVMArg
    val: "-server"
  # Select GC algorithm
  ## Rust MMTk
  mmtk_gc:
    type: EnvVar
    val: "MMTK_PLAN={0}"
  ss:
    type: EnvVar
    val: "MMTK_PLAN=SemiSpace"
  ix:
    type: EnvVar
    val: "MMTK_PLAN=Immix"
  ## OpenJDK HotSpot
  hotspot_gc:
    type: JVMArg
    val: "-XX:-UseCompressedOops -XX:+UnlockExperimentalVMOptions -XX:+Use{0}GC"
  sgc:
    type: JVMArg
    val: "-XX:+UseSerialGC"
  g1:
    type: JVMArg
    val: "-XX:-UseCompressedOops -XX:+UseG1GC"
  epsilon:
    type: JVMArg
    val: "-XX:-UseCompressedOops -XX:+UnlockExperimentalVMOptions -XX:+UseEpsilonGC -XX:-EpsilonElasticTLAB -XX:TLABSize=32K -XX:-ResizeTLAB"
  cms:
    type: JVMArg
    val: "-XX:-UseCompressedOops -XX:+UseConcMarkSweepGC -XX:TLABSize=32K -XX:-ResizeTLAB"